
package com.kunyan;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MailUtilWebService", targetNamespace = "http://zxc/", wsdlLocation = "http://10.5.27.27:9588/MailWebService/service/HadoopMailWeb?wsdl")
public class MailUtilWebService
    extends Service
{

    private final static URL MAILUTILWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILUTILWEBSERVICE_EXCEPTION;
    private final static QName MAILUTILWEBSERVICE_QNAME = new QName("http://zxc/", "MailUtilWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.5.27.27:9588/MailWebService/service/HadoopMailWeb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAILUTILWEBSERVICE_WSDL_LOCATION = url;
        MAILUTILWEBSERVICE_EXCEPTION = e;
    }

    public MailUtilWebService() {
        super(__getWsdlLocation(), MAILUTILWEBSERVICE_QNAME);
    }

    public MailUtilWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILUTILWEBSERVICE_QNAME, features);
    }

    public MailUtilWebService(URL wsdlLocation) {
        super(wsdlLocation, MAILUTILWEBSERVICE_QNAME);
    }

    public MailUtilWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILUTILWEBSERVICE_QNAME, features);
    }

    public MailUtilWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailUtilWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MailUtilWeb
     */
    @WebEndpoint(name = "MailUtilWebPort")
    public MailUtilWeb getMailUtilWebPort() {
        return super.getPort(new QName("http://zxc/", "MailUtilWebPort"), MailUtilWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailUtilWeb
     */
    @WebEndpoint(name = "MailUtilWebPort")
    public MailUtilWeb getMailUtilWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://zxc/", "MailUtilWebPort"), MailUtilWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILUTILWEBSERVICE_EXCEPTION!= null) {
            throw MAILUTILWEBSERVICE_EXCEPTION;
        }
        return MAILUTILWEBSERVICE_WSDL_LOCATION;
    }

}
